name: py37_hn_sparql
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - python=3.7
  - ipykernel
  - ipywidgets
  - pdfplumber
  - seaborn
  - ipyleaflet
  - networkx
  - ipycytoscape
  - ipysankeywidget
